#!/usr/bin/env python3
"""
vsCode-AI Generator v3
Framework de Context Engineering para Firmware Embebido

Genera proyectos PlatformIO completos con contexto embebido para IA
a partir de un catálogo centralizado de hardware y templates.

Autor: @ydiaz1699
"""

import argparse
import sys
import os
import shutil
from pathlib import Path
from datetime import datetime

try:
    import frontmatter
except ImportError:
    print("Error: python-frontmatter no está instalado.")
    print("Ejecuta: pip install -r requirements.txt")
    sys.exit(1)

# === CONSTANTS ===
VERSION = "3.0.0"
BASE_DIR = Path(__file__).parent.resolve()
CATALOG_DIR = BASE_DIR / "catalog"
BOARDS_DIR = CATALOG_DIR / "boards"
PERIPHERALS_DIR = CATALOG_DIR / "peripherals"
ENVIRONMENTS_DIR = CATALOG_DIR / "environments"
TEMPLATES_DIR = BASE_DIR / "templates" / "_base"
OUTPUT_DIR = BASE_DIR / "outputs"



# === UTILITY FUNCTIONS ===

def load_board(board_id: str) -> dict:
    """Load board metadata from catalog frontmatter."""
    board_file = BOARDS_DIR / f"{board_id}.md"
    if not board_file.exists():
        print(f"Error: Placa '{board_id}' no encontrada en {BOARDS_DIR}")
        print(f"Usa 'list-boards' para ver placas disponibles.")
        sys.exit(1)
    post = frontmatter.load(str(board_file))
    metadata = dict(post.metadata)
    metadata["content"] = post.content
    return metadata


def load_peripheral(peripheral_id: str) -> dict:
    """Load peripheral metadata from catalog frontmatter."""
    periph_file = PERIPHERALS_DIR / f"{peripheral_id}.md"
    if not periph_file.exists():
        print(f"Error: Periférico '{peripheral_id}' no encontrado en {PERIPHERALS_DIR}")
        print(f"Usa 'list-peripherals' para ver periféricos disponibles.")
        sys.exit(1)
    post = frontmatter.load(str(periph_file))
    metadata = dict(post.metadata)
    metadata["content"] = post.content
    return metadata


def load_all_boards() -> list:
    """Load all board metadata from catalog."""
    boards = []
    if not BOARDS_DIR.exists():
        return boards
    for f in sorted(BOARDS_DIR.glob("*.md")):
        post = frontmatter.load(str(f))
        boards.append(dict(post.metadata))
    return boards



def load_all_peripherals() -> list:
    """Load all peripheral metadata from catalog."""
    peripherals = []
    if not PERIPHERALS_DIR.exists():
        return peripherals
    for f in sorted(PERIPHERALS_DIR.glob("*.md")):
        post = frontmatter.load(str(f))
        peripherals.append(dict(post.metadata))
    return peripherals


def inject_variables(content: str, variables: dict) -> str:
    """Replace {{VARIABLE}} placeholders in content."""
    result = content
    for key, value in variables.items():
        placeholder = "{{" + key + "}}"
        result = result.replace(placeholder, str(value))
    return result


def ensure_dir(path: Path):
    """Create directory if it doesn't exist."""
    path.mkdir(parents=True, exist_ok=True)


def print_table(headers: list, rows: list):
    """Print a formatted ASCII table."""
    col_widths = [len(h) for h in headers]
    for row in rows:
        for i, cell in enumerate(row):
            col_widths[i] = max(col_widths[i], len(str(cell)))

    # Header
    header_line = " | ".join(h.ljust(col_widths[i]) for i, h in enumerate(headers))
    separator = "-+-".join("-" * col_widths[i] for i in range(len(headers)))
    print(f" {header_line}")
    print(f" {separator}")

    # Rows
    for row in rows:
        row_line = " | ".join(str(cell).ljust(col_widths[i]) for i, cell in enumerate(row))
        print(f" {row_line}")



# === GENERATORS ===

def generate_platformio_ini(board: dict, peripherals: list) -> str:
    """Generate platformio.ini content based on board metadata."""
    platform = board.get("platform", "espressif32")
    board_id = board.get("board", "esp32dev")
    framework = board.get("framework", "arduino")

    lines = [
        "; PlatformIO Project Configuration",
        f"; Generated by vsCode-AI Generator v{VERSION}",
        f"; Board: {board.get('name', board.get('id', 'unknown'))}",
        f"; Date: {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "[env:default]",
        f"platform = {platform}",
        f"board = {board_id}",
        f"framework = {framework}",
        "monitor_speed = 115200",
    ]

    # Build flags for ESP32
    if "esp32" in platform.lower():
        lines.append("build_flags = ")
        lines.append("    -DCORE_DEBUG_LEVEL=3")
        if board.get("wifi", False):
            lines.append("    -DWIFI_ENABLED=1")

    # Library dependencies from peripherals
    lib_deps = []
    for periph in peripherals:
        lib = periph.get("library", periph.get("lib_deps", ""))
        if lib and lib != "(nativo)":
            lib_deps.append(lib)

    if lib_deps:
        lines.append("lib_deps = ")
        for lib in lib_deps:
            lines.append(f"    {lib}")

    lines.append("")
    return "\n".join(lines)



def generate_main_cpp(board: dict, project_name: str) -> str:
    """Generate src/main.cpp skeleton based on board capabilities."""
    lines = [
        f"/**",
        f" * {project_name}",
        f" * Generated by vsCode-AI Generator v{VERSION}",
        f" * Board: {board.get('name', 'Unknown')}",
        f" * Date: {datetime.now().strftime('%Y-%m-%d')}",
        f" */",
        "",
        "#include <Arduino.h>",
    ]

    if board.get("wifi", False):
        mcu = board.get("mcu", "").lower()
        if "esp32" in mcu:
            lines.append("#include <WiFi.h>")
        elif "esp8266" in mcu:
            lines.append("#include <ESP8266WiFi.h>")
        lines.append('#include "secrets.h"')

    lines.extend([
        "",
        "// === CONFIGURATION ===",
        "#define LED_BUILTIN_PIN 2",
        "",
        "// === GLOBAL VARIABLES ===",
        "",
        "// === FUNCTION PROTOTYPES ===",
        "void initHardware();",
    ])

    if board.get("wifi", False):
        lines.append("void initWiFi();")

    lines.extend([
        "",
        "// === SETUP ===",
        "void setup() {",
        "    Serial.begin(115200);",
        "    delay(1000);",
        f'    Serial.println("\\n[{project_name}] Iniciando...");',
        "",
        "    initHardware();",
    ])

    if board.get("wifi", False):
        lines.append("    initWiFi();")

    lines.extend([
        "",
        f'    Serial.println("[{project_name}] Sistema listo.");',
        "}",
        "",
        "// === LOOP ===",
        "void loop() {",
        "    // TODO: Implementar lógica principal",
        "    delay(1000);",
        "}",
        "",
        "// === IMPLEMENTATIONS ===",
        "void initHardware() {",
        "    pinMode(LED_BUILTIN_PIN, OUTPUT);",
        "    digitalWrite(LED_BUILTIN_PIN, LOW);",
        '    Serial.println("[HW] Hardware inicializado.");',
        "}",
    ])

    if board.get("wifi", False):
        lines.extend([
            "",
            "void initWiFi() {",
            '    Serial.print("[WiFi] Conectando...");',
            "    WiFi.begin(WIFI_SSID, WIFI_PASS);",
            "",
            "    int attempts = 0;",
            "    while (WiFi.status() != WL_CONNECTED && attempts < 20) {",
            "        delay(500);",
            '        Serial.print(".");',
            "        attempts++;",
            "    }",
            "",
            "    if (WiFi.status() == WL_CONNECTED) {",
            "        Serial.println();",
            '        Serial.print("[WiFi] Conectado. IP: ");',
            "        Serial.println(WiFi.localIP());",
            "    } else {",
            '        Serial.println("\\n[WiFi] Error de conexión.");',
            "    }",
            "}",
        ])

    lines.append("")
    return "\n".join(lines)



def generate_secrets_template() -> str:
    """Generate include/secrets.h.template for WiFi credentials."""
    return """#ifndef SECRETS_H
#define SECRETS_H

// === WiFi Configuration ===
// Copy this file to secrets.h and fill in your credentials
// NEVER commit secrets.h to version control

#define WIFI_SSID "your-wifi-ssid"
#define WIFI_PASS "your-wifi-password"

// === MQTT Configuration (optional) ===
// #define MQTT_BROKER "192.168.1.100"
// #define MQTT_PORT 1883
// #define MQTT_USER "mqtt-user"
// #define MQTT_PASS "mqtt-password"

// === API Keys (optional) ===
// #define API_KEY "your-api-key"

#endif // SECRETS_H
"""


def generate_project_context(project_name: str, board: dict, description: str) -> str:
    """Generate .ai/PROJECT_CONTEXT.md content."""
    return f"""# {project_name} — Project Context

## Overview
- **Project**: {project_name}
- **Description**: {description}
- **Board**: {board.get('name', 'Unknown')} ({board.get('mcu', 'Unknown')})
- **Framework**: {board.get('framework', 'arduino')}
- **Generated**: {datetime.now().strftime('%Y-%m-%d')}
- **Generator**: vsCode-AI v{VERSION}

## Hardware Summary
- **MCU**: {board.get('mcu', 'Unknown')}
- **Flash**: {board.get('flash', 'N/A')}
- **RAM**: {board.get('ram', 'N/A')}
- **WiFi**: {'Yes' if board.get('wifi') else 'No'}
- **Bluetooth**: {'Yes' if board.get('bluetooth') else 'No'}

## Project Goals
1. {description}
2. Mantener código limpio y documentado
3. Seguir las convenciones de PlatformIO

## Constraints
- Memory-constrained environment (embedded)
- Real-time operation requirements
- Power efficiency considerations
"""



def generate_architecture(project_name: str, board: dict) -> str:
    """Generate .ai/ARCHITECTURE.md content."""
    return f"""# {project_name} — Architecture

## System Overview

```
┌─────────────────────────────────────┐
│           {board.get('name', 'MCU'):^25} │
├─────────────────────────────────────┤
│  Application Layer                  │
│  ├── Main Loop                      │
│  ├── Task Scheduler                 │
│  └── State Machine                  │
├─────────────────────────────────────┤
│  Hardware Abstraction Layer (HAL)   │
│  ├── GPIO Manager                   │
│  ├── Communication (I2C/SPI/UART)   │
│  └── WiFi/Network Stack             │
├─────────────────────────────────────┤
│  Platform: {board.get('framework', 'arduino'):^23} │
└─────────────────────────────────────┘
```

## Directory Structure
- `src/` — Main application code
- `include/` — Header files and configuration
- `lib/` — Project-specific libraries
- `test/` — Unit and integration tests
- `docs/` — Project documentation

## Design Principles
1. **Modular** — Each component is self-contained
2. **Testable** — Logic separated from hardware access
3. **Documented** — Every module has clear purpose
4. **Efficient** — Minimal memory footprint
"""


def generate_protocol() -> str:
    """Generate .ai/PROTOCOL.md content."""
    return f"""# AI Interaction Protocol

## Rules for AI Assistants

### Before Writing Code
1. Read PROJECT_CONTEXT.md to understand the project
2. Read ARCHITECTURE.md for structural decisions
3. Check HARDWARE.md for pin assignments and constraints
4. Review CODING_STYLE.md for conventions

### When Writing Code
- Use PlatformIO conventions
- Keep functions under 30 lines
- Add comments for non-obvious logic
- Use meaningful variable names (English)
- Handle errors gracefully (no silent failures)

### Memory Constraints
- Avoid dynamic allocation (malloc/new) when possible
- Use stack-allocated buffers with fixed sizes
- Prefer `const` and `constexpr` for constants
- Be mindful of String fragmentation on ESP32/Arduino

### Communication
- Serial output format: `[MODULE] Message`
- Use debug levels: ERROR, WARN, INFO, DEBUG
- Never print credentials or secrets

### File Organization
- One class per file
- Header guards in all .h files
- Include only what you use
"""



def generate_project_readme(project_name: str, board: dict, description: str) -> str:
    """Generate README.md for the generated project."""
    return f"""# {project_name}

> {description}

## Hardware

- **Board**: {board.get('name', 'Unknown')}
- **MCU**: {board.get('mcu', 'Unknown')}
- **Platform**: PlatformIO ({board.get('framework', 'arduino')})

## Quick Start

```bash
# Compilar
pio run

# Subir al dispositivo
pio run --target upload

# Monitor serial
pio device monitor
```

## Configuration

1. Copy `include/secrets.h.template` to `include/secrets.h`
2. Fill in your WiFi credentials (if applicable)
3. Adjust pin definitions in `include/` as needed

## Project Structure

- `src/main.cpp` — Entry point
- `include/` — Configuration and headers
- `lib/` — Custom libraries
- `test/` — Unit tests
- `.ai/` — AI assistant context
- `docs/` — Documentation

## Generated By

vsCode-AI Generator v{VERSION} — {datetime.now().strftime('%Y-%m-%d')}
"""


# === COMMANDS ===

def cmd_new(args):
    """Generate a new project from catalog."""
    board_id = args.board
    project_name = args.name
    description = args.desc or f"Proyecto {project_name} con {board_id}"
    output_base = Path(args.output) if args.output else OUTPUT_DIR

    print(f"\n{'='*60}")
    print(f"  vsCode-AI Generator v{VERSION}")
    print(f"  Generando proyecto: {project_name}")
    print(f"{'='*60}\n")

    # Load board
    board = load_board(board_id)
    print(f"  [✓] Board: {board.get('name')} ({board.get('mcu')})")

    # Load peripherals
    peripherals = []
    if args.peripheral:
        for p_id in args.peripheral:
            periph = load_peripheral(p_id)
            peripherals.append(periph)
            print(f"  [✓] Periférico: {periph.get('name')} ({periph.get('protocol', 'N/A')})")

    # Create project directory
    project_dir = output_base / project_name
    if project_dir.exists():
        print(f"\n  [!] El directorio ya existe: {project_dir}")
        print(f"      Usa otro nombre o elimina el directorio existente.")
        sys.exit(1)

    print(f"\n  Creando estructura en: {project_dir}\n")


    # Create folder structure
    folders = [
        project_dir / ".ai",
        project_dir / "src",
        project_dir / "include",
        project_dir / "lib",
        project_dir / "test",
        project_dir / "docs",
        project_dir / ".vscode",
    ]
    for folder in folders:
        ensure_dir(folder)
        print(f"  [+] {folder.relative_to(project_dir)}/")

    # Template variables
    variables = {
        "PROJECT_NAME": project_name,
        "BOARD_ID": board_id,
        "BOARD_NAME": board.get("name", "Unknown"),
        "MCU": board.get("mcu", "Unknown"),
        "PLATFORM": board.get("platform", "espressif32"),
        "FRAMEWORK": board.get("framework", "arduino"),
        "DATE": datetime.now().strftime("%Y-%m-%d"),
        "DATETIME": datetime.now().isoformat(),
        "VERSION": VERSION,
        "DESCRIPTION": description,
        "WIFI": "true" if board.get("wifi") else "false",
        "BLUETOOTH": "true" if board.get("bluetooth") else "false",
        "FLASH": board.get("flash", "N/A"),
        "RAM": board.get("ram", "N/A"),
    }

    # Generate .ai/ files
    print("\n  Generando contexto IA (.ai/)...")

    ai_files = {
        "PROJECT_CONTEXT.md": generate_project_context(project_name, board, description),
        "ARCHITECTURE.md": generate_architecture(project_name, board),
        "PROTOCOL.md": generate_protocol(),
    }

    for filename, content in ai_files.items():
        filepath = project_dir / ".ai" / filename
        filepath.write_text(inject_variables(content, variables), encoding="utf-8")
        print(f"  [+] .ai/{filename}")

    # Generate platformio.ini
    print("\n  Generando configuración PlatformIO...")
    pio_content = generate_platformio_ini(board, peripherals)
    (project_dir / "platformio.ini").write_text(pio_content, encoding="utf-8")
    print(f"  [+] platformio.ini")

    # Generate src/main.cpp
    print("\n  Generando código fuente...")
    main_content = generate_main_cpp(board, project_name)
    (project_dir / "src" / "main.cpp").write_text(main_content, encoding="utf-8")
    print(f"  [+] src/main.cpp")

    # Generate secrets.h.template if WiFi
    if board.get("wifi", False):
        secrets_content = generate_secrets_template()
        (project_dir / "include" / "secrets.h.template").write_text(secrets_content, encoding="utf-8")
        print(f"  [+] include/secrets.h.template")

    # Copy .vscode/ files if available
    vscode_src = ENVIRONMENTS_DIR / "vscode"
    if vscode_src.exists():
        print("\n  Copiando configuración VSCode...")
        for f in vscode_src.iterdir():
            if f.is_file():
                shutil.copy2(f, project_dir / ".vscode" / f.name)
                print(f"  [+] .vscode/{f.name}")
    else:
        # Generate default .vscode files
        extensions_json = '{\n    "recommendations": [\n        "platformio.platformio-ide"\n    ]\n}\n'
        (project_dir / ".vscode" / "extensions.json").write_text(extensions_json, encoding="utf-8")
        print(f"  [+] .vscode/extensions.json (default)")

    # Copy tooling files if available
    tooling_src = ENVIRONMENTS_DIR / "tooling"
    if tooling_src.exists():
        print("\n  Copiando archivos de tooling...")
        for f in tooling_src.iterdir():
            if f.is_file():
                shutil.copy2(f, project_dir / f.name)
                print(f"  [+] {f.name}")


    # Generate project README
    readme_content = generate_project_readme(project_name, board, description)
    (project_dir / "README.md").write_text(readme_content, encoding="utf-8")
    print(f"  [+] README.md")

    # Generate .gitignore for project
    gitignore_content = """# PlatformIO
.pio/
.pioenvs/
.piolibdeps/

# IDE
.vscode/.browse.c_cpp.db*
.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/ipch

# Secrets
include/secrets.h

# OS
.DS_Store
Thumbs.db
"""
    (project_dir / ".gitignore").write_text(gitignore_content, encoding="utf-8")
    print(f"  [+] .gitignore")

    # Summary
    print(f"\n{'='*60}")
    print(f"  ✅ Proyecto generado exitosamente!")
    print(f"{'='*60}")
    print(f"  📁 Ubicación: {project_dir}")
    print(f"  🔧 Board: {board.get('name')} ({board.get('mcu')})")
    if peripherals:
        print(f"  📡 Periféricos: {', '.join(p.get('name', p.get('id')) for p in peripherals)}")
    print(f"\n  Próximos pasos:")
    print(f"  1. cd {project_dir}")
    if board.get("wifi"):
        print(f"  2. cp include/secrets.h.template include/secrets.h")
        print(f"  3. Edita secrets.h con tus credenciales")
        print(f"  4. pio run --target upload")
    else:
        print(f"  2. pio run --target upload")
    print()


def cmd_add_peripheral(args):
    """Add a peripheral to an existing project."""
    project_path = Path(args.project).resolve()
    peripheral_id = args.peripheral

    if not project_path.exists():
        print(f"Error: Proyecto no encontrado en {project_path}")
        sys.exit(1)

    pio_ini = project_path / "platformio.ini"
    if not pio_ini.exists():
        print(f"Error: No se encontró platformio.ini en {project_path}")
        print(f"       ¿Es un proyecto PlatformIO válido?")
        sys.exit(1)

    # Load peripheral
    periph = load_peripheral(peripheral_id)
    lib = periph.get("library", periph.get("lib_deps", ""))

    print(f"\n  Agregando periférico: {periph.get('name')}")
    print(f"  Protocolo: {periph.get('protocol', 'N/A')}")
    print(f"  Categoría: {periph.get('category', 'N/A')}")

    if lib and lib != "(nativo)":
        # Read current platformio.ini
        content = pio_ini.read_text(encoding="utf-8")

        if lib in content:
            print(f"\n  [!] La librería '{lib}' ya está en platformio.ini")
            return

        # Add lib_deps
        if "lib_deps" in content:
            # Append to existing lib_deps
            content = content.replace("lib_deps = \n", f"lib_deps = \n    {lib}\n", 1)
            if f"    {lib}" not in content:
                # Try alternate format
                lines = content.split("\n")
                for i, line in enumerate(lines):
                    if line.strip().startswith("lib_deps"):
                        # Find last lib_dep line
                        j = i + 1
                        while j < len(lines) and lines[j].startswith("    "):
                            j += 1
                        lines.insert(j, f"    {lib}")
                        content = "\n".join(lines)
                        break
        else:
            content += f"\nlib_deps = \n    {lib}\n"

        pio_ini.write_text(content, encoding="utf-8")
        print(f"  [✓] Agregado a platformio.ini: {lib}")
    else:
        print(f"  [i] Este periférico no requiere librería externa (uso nativo GPIO)")

    print(f"\n  ✅ Periférico '{periph.get('name')}' agregado al proyecto.")
    print()



def cmd_list_boards(args):
    """List all available boards from catalog."""
    boards = load_all_boards()

    if not boards:
        print("\n  No se encontraron placas en el catálogo.")
        print(f"  Directorio esperado: {BOARDS_DIR}")
        print(f"  Agrega archivos .md con frontmatter YAML.")
        return

    print(f"\n  Placas disponibles ({len(boards)}):\n")

    headers = ["ID", "Nombre", "MCU", "WiFi", "BT", "Precio"]
    rows = []
    for b in boards:
        rows.append([
            b.get("id", "?"),
            b.get("name", "?"),
            b.get("mcu", "?"),
            "✅" if b.get("wifi") else "❌",
            "✅" if b.get("bluetooth") else "❌",
            b.get("price", "?"),
        ])

    print_table(headers, rows)
    print()


def cmd_list_peripherals(args):
    """List all available peripherals from catalog."""
    peripherals = load_all_peripherals()

    if not peripherals:
        print("\n  No se encontraron periféricos en el catálogo.")
        print(f"  Directorio esperado: {PERIPHERALS_DIR}")
        print(f"  Agrega archivos .md con frontmatter YAML.")
        return

    print(f"\n  Periféricos disponibles ({len(peripherals)}):\n")

    headers = ["ID", "Nombre", "Protocolo", "Categoría"]
    rows = []
    for p in peripherals:
        rows.append([
            p.get("id", "?"),
            p.get("name", "?"),
            p.get("protocol", "?"),
            p.get("category", "?"),
        ])

    print_table(headers, rows)
    print()


def cmd_version(args):
    """Print version information."""
    print(f"\n  vsCode-AI Generator v{VERSION}")
    print(f"  Framework de Context Engineering para Firmware Embebido")
    print(f"  Base: {BASE_DIR}")
    print(f"  Catálogo: {CATALOG_DIR}")
    print()



# === MAIN ===

def main():
    """Main entry point with argparse subcommands."""
    parser = argparse.ArgumentParser(
        prog="generator.py",
        description=f"vsCode-AI Generator v{VERSION} — Context Engineering para Firmware Embebido",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Ejemplos:
  python generator.py new --board esp32-devkit --name mi-proyecto
  python generator.py new --board esp32-s3 --name sensor --peripheral dht22 --peripheral bme280
  python generator.py add-peripheral --project ./mi-proyecto --peripheral relay-4ch
  python generator.py list-boards
  python generator.py list-peripherals
  python generator.py version
        """,
    )

    subparsers = parser.add_subparsers(dest="command", help="Comando a ejecutar")

    # === new ===
    parser_new = subparsers.add_parser("new", help="Generar un nuevo proyecto")
    parser_new.add_argument("--board", required=True, help="ID de la placa (ver list-boards)")
    parser_new.add_argument("--name", required=True, help="Nombre del proyecto")
    parser_new.add_argument(
        "--peripheral", action="append", default=[],
        help="ID de periférico a incluir (puede repetirse)"
    )
    parser_new.add_argument("--desc", help="Descripción del proyecto")
    parser_new.add_argument("--output", help="Directorio de salida (default: outputs/)")
    parser_new.set_defaults(func=cmd_new)

    # === add-peripheral ===
    parser_add = subparsers.add_parser("add-peripheral", help="Agregar periférico a proyecto existente")
    parser_add.add_argument("--project", required=True, help="Ruta al proyecto")
    parser_add.add_argument("--peripheral", required=True, help="ID del periférico")
    parser_add.set_defaults(func=cmd_add_peripheral)

    # === list-boards ===
    parser_lb = subparsers.add_parser("list-boards", help="Listar placas disponibles")
    parser_lb.set_defaults(func=cmd_list_boards)

    # === list-peripherals ===
    parser_lp = subparsers.add_parser("list-peripherals", help="Listar periféricos disponibles")
    parser_lp.set_defaults(func=cmd_list_peripherals)

    # === version ===
    parser_v = subparsers.add_parser("version", help="Mostrar versión")
    parser_v.set_defaults(func=cmd_version)

    # Parse and execute
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    args.func(args)


if __name__ == "__main__":
    main()
