repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c, c++]
        args: [--style=file]

  - repo: local
    hooks:
      - id: platformio-check
        name: PlatformIO Static Analysis
        entry: pio check --skip-packages
        language: system
        types_or: [c, c++]
        pass_filenames: false
